config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  # resources :participations, only: [:create], shallow: true
  resources :hunts, only: [:index, :show], shallow: true  do
    member do
      get :play
      post :check
    end
    resources :checkpoints, only: [] do
      member do
        post :check
        get :next
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :hunts
end

app/models/checkpoint.rb
class Checkpoint < ApplicationRecord
  has_many :participations
  belongs_to :hunt
  acts_as_list scope: :hunt

  def lat_lng
    "#{lat},#{log}"
  end
  


end

app/models/hunt.rb
class Hunt < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :checkpoints, -> { order(position: :asc) }
  has_many :participations

  geocoded_by :city
  after_validation :geocode, if: :city_changed?

  accepts_nested_attributes_for :checkpoints

  def self.search(city, category_id)
    if !city.empty? && !category_id.empty?
      self.where(category_id: category_id).near(city, 200)
    elsif !city.empty?
      self.all.near(city, 200)
    elsif !category_id.empty?
      self.where(category_id: category_id)
    else
      self.all
    end
  end

  def gmap_path
    path.map { |(lat, log)| "#{lat},#{log}" }.join("|")
  end

  def path
    checkpoints.order(position: :asc).pluck(:lat, :log)
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :hunt
  belongs_to :user
  belongs_to :checkpoint
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :hunts
  has_many :participations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

def default_url_options
  { host: ENV["https://www.escapincity.com"] }
end

app/controllers/checkpoints_controller.rb
class CheckpointsController < ApplicationController
  def check
  end

  def next
  end
end

app/controllers/hunts_controller.rb
class HuntsController < ApplicationController
  layout "hunts_layout", except: [:index, :show]

  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_hunt, only: %i(show play check)

  def index
    if params[:hunt]
      city = params[:hunt][:city]
      category_id = params[:hunt][:category]
      @hunts = Hunt.order(created_at: :desc).search(city, category_id)
    else
      @hunts = Hunt.order(created_at: :desc)
    end
  end

  def show
    @waypoints = @hunt.checkpoints
    # .map do |cp|
    #   {location: [cp.lat, cp.log], stopover: true}
    # end

    # @waypoints = Gmaps4rails.build_markers(@waypoints) do |check, marker|
    #   marker.lat check.lat
    #   marker.lng check.log
    # end

  end

  def play

    @checkpoint = @hunt.checkpoints.first

    @hash = Gmaps4rails.build_markers(@checkpoint) do |check, marker|
      marker.lat check.lat
      marker.lng check.log
      marker.title "#checkpoint = " + @checkpoint.position.to_s

      marker.infowindow "
        <div id='info-window-marker'> <div id='img-check'> <img src='#{view_context.image_url(check.photo)}' class='info_window'> </div>
        <p class='info_window_text'>#{@checkpoint.description}</p> </div>
      "
    end
  end

  def check

    checkpoint_id = params[:check][:checkpoint_id]
    @current_checkpoint = @hunt.checkpoints.find(checkpoint_id)

    @latitude = params[:check][:latitude]
    @longitude = params[:check][:longitude]
    accuracy = params[:check][:accuracy]

    loc_nav = [@latitude, @longitude]
    loc_checkpoint = [@current_checkpoint.lat , @current_checkpoint.log ]

    distance = Geocoder::Calculations.distance_between(loc_nav,loc_checkpoint)

     if @current_checkpoint.id == @hunt.checkpoints.last.id
       @end_of_game = true
     else

      if distance < (30 + accuracy.to_f) # 0.03 supposed min distance to treasure
        if @current_checkpoint.last?
          @checkpoint_fail = true
        else
          @checkpoint = @current_checkpoint.lower_item

        end
      else
        @checkpoint = @current_checkpoint
        @show_content = nil
        @checkpoint_fail = true
      end
      @hash = Gmaps4rails.build_markers(@checkpoint) do |check, marker|
        marker.lat check.lat
        marker.lng check.log

        marker.infowindow"
        <div id='info-window-marker'> <div id='img-check'> <img src='#{view_context.image_url(check.photo)}' class='info_window'> </div>
        <p class='info_window_text'>#{@checkpoint.description}</p> </div>
        "

      end
    end
  end

  private

  def search_params
    params.require(:hunt).permit(:city, :category)
  end

  def set_hunt
    @hunt = Hunt.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/checkpoints/check.html.erb
<h1>Checkpoints#check</h1>
<p>Find me in app/views/checkpoints/check.html.erb</p>

app/views/checkpoints/next.html.erb
<h1>Checkpoints#next</h1>
<p>Find me in app/views/checkpoints/next.html.erb</p>

app/views/hunts/_hunt_content.html.erb
<%#= link_to 'verify', check_hunt_path(hunt, checkpoint_id: checkpoint.id, lat: crd.latitude, lng: crd.longitude ), method: :post, remote: true %>
<div class="modal fade bs-example-modal-sm common-modal-css modal-clue" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <P> <%= checkpoint.clue  %> </P>


    </div>
  </div>
</div>

<P> <img <%= image_url 'bluecircle.png'  %>> </P>

<div id="map"></div>

<%= simple_form_for :check, url: check_hunt_path(@hunt), method: :post, remote: true, html: { id: "check-form" } do |f| %>
  <%= f.input :checkpoint_id, input_html: { value: @checkpoint.id }, :as => :hidden %>
  <%= f.input :latitude , :as => :hidden %>
  <%= f.input :longitude, :as => :hidden %>
  <%= f.input :accuracy ,:as => :hidden %>
<% end %>

<%= link_to 'verify location', '#', class: "btn btn-primary btn-lg", id: "btn-verify"%>

<button type="button" class="btn btn-primary my-modal-button" data-toggle="modal" data-target=".bs-example-modal-sm" id="btn-clue">Show a Clue</button>

app/views/hunts/check.js.erb
<% unless @end_of_game %>
  $('#hunt-contents').html("<%= j render 'hunt_content', hunt: @hunt, checkpoint: @checkpoint %>")

  $(document).ready(function() {
    var mapStyle = [{"featureType":"landscape.natural","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#e0efef"}]},{"featureType":"poi","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"hue":"#1900ff"},{"color":"#c0e8e8"}]},{"featureType":"road","elementType":"geometry","stylers":[{"lightness":100},{"visibility":"simplified"}]},{"featureType":"road","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"transit.line","elementType":"geometry","stylers":[{"visibility":"on"},{"lightness":700}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#7dcdcd"}]}]

    var handler = Gmaps.build('Google');
    handler.buildMap({
    internal: { id: 'map' },
    provider: {
      styles: mapStyle,
      gestureHandling: 'greedy'
      }
    }, function() {
      circle = [{lng: <%= @checkpoint.log %>, lat: <%= @checkpoint.lat %>, radius: 100, color: '#FFFFFF'}]
      var markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(16);
      handler.addCircles(circle)
    });
  });

  // update checkoint_id field
  $('#check_checkpoint_id').val(<%= @checkpoint.id %>)
  <% if @checkpoint_fail %>
    $('#fail-modal .modal-body').html('<%= @checkpoint.clue %>');
    $('#fail-modal').modal('show');
  <% else %>
    $('#content-modal .modal-body').html('<%= @current_checkpoint.content %>');
    $('#content-modal').modal('show');
  <% end %>

<% else %>

   <% if @end_of_game %>
    $('#end-modal .modal-body').html('Congrads you won');
    $('#end-modal').modal('show');
   <% end %>

<% end %>

app/views/hunts/index.html.erb
<div class="container">
  <h1>Our crazy escapes 🤠</h1>
  <div class="row">
    <% @hunts.each do |hunt| %>
      <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="hunt-card-wrapper">
          <%= link_to hunt_path(hunt) do %>
            <div class="hunt-card">
              <div class="top-hunt-card" style="background-image: url(<%= asset_path "#{hunt.category.photo}" %>)">
              </div>
              <div class="bottom-hunt-card">
                <div class="card-description">
                  <h2><%= hunt.name.capitalize %></h2>
                  <p id="categ">Category : <%=hunt.category.name.capitalize %></p>
                  <p>City : <%= hunt.city %></p>
                  <p>Distance : <%= hunt.mydistance %>km</p>
                  <p>Difficulty : <%= hunt.difficulty %> / 5</p>
                  <p>Created by : </p>
                </div>
                <div class="card-author">
                  <%= image_tag "user.jpg", class: "avatar-large" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/hunts/play.html.erb
<div class="my-body">
  <div class="my-content">
    <div class="hunt-content">

      <div id="hunt-contents">
        <%= render 'hunt_content', hunt: @hunt, checkpoint: @checkpoint %>
      </div>

      <div class="modal fade common-modal-css" id="content-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3>Well done! You found the checkpoint! &nbsp&nbsp<i id="green-check"  class="fa fa-check"></i><i id="green-check"  class="fa fa-check"></i>
        </h3>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-dismiss="modal">start the next checkpoint</button>
      </div>
      </div>
    </div>
  </div>

    <div class="modal fade common-modal-css" id="fail-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h3>Getting closer, try again! &nbsp&nbsp&nbsp<i class="fa fa-times"></i><i class="fa fa-times"></i></h3>
          </div>
          <div class="modal-body"></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Try again</button>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="end-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h3>You reached the last checkpoint, congrats!<i class="fa fa-cross"></i></h3>
          </div>
          <div class="modal-body">
          </div>
          <div class="modal-footer">
            <%= link_to "Check the other hunts", hunts_path(), class: "btn btn-default" %>
            </div>
        </div>
      </div>
    </div>

    <% content_for(:after_js) do %>
      <script>
        $(document).ready(function() {
          var mapStyle = [{"featureType":"landscape.natural","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#e0efef"}]},{"featureType":"poi","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"hue":"#1900ff"},{"color":"#c0e8e8"}]},{"featureType":"road","elementType":"geometry","stylers":[{"lightness":100},{"visibility":"simplified"}]},{"featureType":"road","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"transit.line","elementType":"geometry","stylers":[{"visibility":"on"},{"lightness":700}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#7dcdcd"}]}]

          circle = [{lng: <%= @checkpoint.log %>, lat: <%= @checkpoint.lat %>, radius: 100, strokeColor: '#0000FF'}]
          var handler = Gmaps.build('Google');
          handler.buildMap({
          internal: { id: 'map' },
          provider: {
            styles: mapStyle,
            gestureHandling: 'greedy'
            }
          },function() {
            markers = handler.addMarkers(<%= raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            handler.getMap().setZoom(16);
            handler.addCircles(circle)
          });

          var options = {
            timeout: 10000,
            enableHighAccuracy: true,
            maximumAge: 0
          };
          var userMarker = null;

          setUserPositionOnMap();
          setInterval(setUserPositionOnMap, 9000);

          function setUserPositionOnMap() {
            navigator.geolocation.getCurrentPosition(setPosition, error,  {timeout: 10000});
          }

          function setPosition(position) {
            if (userMarker) {
              userMarker.setMap(null);
            }
            userMarker = new google.maps.Marker({
              position: new google.maps.LatLng(position.coords.latitude, position.coords.longitude),
              map: handler.getMap(),
              icon: "<%= image_url 'bluecircle.png' %>"
            });
          }

          // bind click on verify
          $('body').on('click', '#btn-verify', function(e){
            e.preventDefault();
            navigator.geolocation.getCurrentPosition(success, error, options);
          });

          function success(pos) {
            var crd = pos.coords;
            $('#check_latitude').val(crd.latitude);
            $('#check_longitude').val(crd.longitude);
            $('#check_accuracy').val(crd.accuracy);

            $('#check-form').trigger('submit');
          }
          function error(err) {
            console.warn("ERROR(${err.code}): ${err.message}");
          };


        });
      </script>
    <% end %>
    </div>
  </div>
</div>

app/views/hunts/show.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-6">
      <div class="side-menu">
        <div id="hunt-title-category">
          <h1><%= @hunt.name %><br><%= @hunt.category.name %></h1>
        </div>
        <div class="distance-info">
          <p>Distance : 5.0 km</p>
          <p>Difficulty : 3/5</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="map-test" style="width: 100%; height: 350px"></div>

<div id="hunt-description">
  <p class="hunt-desc-text">Mystic Burdigala is the perfect choice for people who wants to discover Bordeaux with some never seen angles before! <br><br>
  Quite a lot of beautiful sight seeing and famous spots that totally worths the medium difficulty required for this escape. Such a perfect way to dig out all the hidden treasures of the magnificent Bordeaux!</p>
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <%= link_to "Back", :back,  class: "btn btn-success btn-lg margin-button design-button" %>
    </div>
    <div class="col-xs-6 text-right">
      <%= simple_form_for :hunt, url: play_hunt_path(@hunt), method: :get do |f| %>
        <%= f.button :submit, "Go !", class: "btn btn-success btn-lg margin-button design-button"%>
      <% end %>

    </div>
  </div>
</div>

<% content_for(:after_js) do %>

<script>
  var directionsDisplay = new google.maps.DirectionsRenderer();
  var directionsService = new google.maps.DirectionsService();

  function calcRoute() {
    var origin      = new google.maps.LatLng(<%= @waypoints.first.lat_lng %>);
    var destination = new google.maps.LatLng(<%= @waypoints.last.lat_lng %>);

    var request = {
      origin: origin,
      destination: destination,
      <% if @waypoints.size > 2 %>
        waypoints: [
          <% @waypoints[1..-2].each do |waypoint| %>
            {
              location: new google.maps.LatLng(<%= waypoint.lat_lng %>),
              stopover: true
            },
          <% end %>
        ],
      <% end %>
      travelMode: google.maps.TravelMode.WALKING,
    };
    directionsService.route(request, function(response, status) {
      if (status == google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(response);
      }
    });
  }

  calcRoute(); // call this anywhere you want
  $(document).ready(function(){

    var mapStyle = [{"featureType":"landscape.natural","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#e0efef"}]},{"featureType":"poi","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"hue":"#1900ff"},{"color":"#c0e8e8"}]},{"featureType":"road","elementType":"geometry","stylers":[{"lightness":100},{"visibility":"simplified"}]},{"featureType":"road","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"transit.line","elementType":"geometry","stylers":[{"visibility":"on"},{"lightness":700}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#7dcdcd"}]}]

    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map-test' }}, function() {

    var handler = Gmaps.build('Google');
    handler.buildMap({
      internal: { id: 'map-test' },
      provider: {
        styles: mapStyle
      }
    }, function() {
      directionsDisplay.setMap(handler.getMap());
    });
  });
});

</script>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= meta_title %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>
  <body>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div class="content">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=#{ENV['API_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/layouts/hunts_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Escapin City</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>


      <%= yield %>



    <%= javascript_include_tag "https://maps.google.com/maps/api/js?key=#{ENV['API_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= asset_path "background.jpg" %>' );">
  <div class="banner-content">
    <h1>Go. Find the magic.</h1>
    <div class="container">
      </div>
        <%= simple_form_for :hunt, url: hunts_path, method: :get do |f| %>
          <div class="form-group row">
              <%= f.input :city, placeholder: "Enter a city", id: 'city', label: false %>

              <%= f.input :category, collection: @categories, prompt: "Pick a category", id: 'category', label: false %>

              <%= f.button :submit, "Find an Escape", class: "btn btn-primary btn-lg", id: 'search-btn' %>
          </div>
          </div>
        <% end %>
      </div>

  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- <% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %> -->

app/views/shared/_footer.html.erb
<div class="footer text-center <%= yield(:footer_class)%>">
  <div class="footer-left">
    <p id= "p1">Project creators :</p>
    <p id= "p1">Baturay, Florian & Heritiana</p>
    <p id= "p1">Batch#67 Le Wagon</p>
  </div>
  <div class="footer-mid">
    <a href="http://twitter.com">
      <i class='fa fa-twitter'></i>
    </a>
    <a href="http://facebook.com">
      <i class='fa fa-facebook'></i>
    </a>
    <a href="http://instagram.com">
      <i class='fa fa-instagram'></i>
    </a>
  </div>
  <div class="footer-right">
    <p id= "p2">Escapin' City | info@batch67.com :</p>
    <p id= "p2">Privacy Policy - Terms of Service</p>
    <p id= "p2">©2017 Escapin'City Ruby on Rails</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "Logo_final.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <!--<form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

        <a class="a1" href="#">Create</a>
        <a class="a1" href="#">Help</a>


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "https://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <!-- < %=link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %> -->
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item <!-- hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="/users/sign_in">Login</a></li>
        <li><a href="#">Create</a></li>
        <li><a href="#">Help</a></li>
      </ul>
    </div>
  </div>
</div>

<!-- x -->